## Numpy Notes


In [1]:
import numpy as np 

lista = [1,2,3,4]
print(type(lista))
arreglo = np.array(lista)
print(type(arreglo))

tupla = (1,2,3,4)
print(type(tupla))
arreglo2 = np.array(tupla)
print(type(arreglo2))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>


#### Dimensiones 

Las formas de los arrays se pueden ver con .shape()

In [2]:
import numpy as np 

arr1 = np.array([    #tiene dos dimenciones y es una matriz 2x3
    [1, 2, 3],
    [4, 5, 6]
])
print(arr1.shape)

(2, 3)


In [3]:
import numpy as np
# Arreglo 4D (2 bloques, 2 matrices por bloque, 3 filas por matriz, 4 columnas por fila)
arr_4d = np.array([
    [  
        [   
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]
        ],
        [   
            [13, 14, 15, 16],
            [17, 18, 19, 20],
            [21, 22, 23, 24]
        ]
    ],
    [   
        [   # Matriz 2.1
            [25, 26, 27, 28],
            [29, 30, 31, 32],
            [33, 34, 35, 36]
        ],
        [  
            [37, 38, 39, 40],
            [41, 42, 43, 44],
            [45, 46, 47, 48]
        ]
    ]
])

print("Shape:", arr_4d.shape)  # Salida: (2, 2, 3, 4)
print("Número de dimensiones:", arr_4d.ndim)  # Salida: 4

Shape: (2, 2, 3, 4)
Número de dimensiones: 4


### reshape 
Es una forma de reorganizar un array cambiandole la forma 

In [4]:
import numpy as np

# Crear un array de 1 dimensión con 6 elementos
arr = np.array([1, 2, 3, 4, 5, 6])

# Cambiar la forma del array a 2 filas por 3 columnas
nuevo_arr = arr.reshape(2, 3)

print(arr)
print(' ')
print(nuevo_arr)


[1 2 3 4 5 6]
 
[[1 2 3]
 [4 5 6]]


### operacion elemento a elemento 

Son operaciones que se realizan sobre cada elemento 

In [5]:
import numpy as np 

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b) # Suma
print(a - b) # Resta
print(a * b) # Multiplicación elemento a elemento
print(a / b) # División elemento a elemento

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


### operaciones gregadas 

Estas operaciones son propias de numpy, la mayot ventaja de estas es que se desbloquea el concepto de axis.

In [1]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.sum(arr))       # 10 (suma total)
print(np.sum(arr, axis=0))  # [4, 6] (suma por columnas)

10
[4 6]


In [2]:
arr = np.array([[1, 2], [3, 4]])
print(np.mean(arr))       # 2.5 (promedio total)
print(np.mean(arr, axis=1))  # [1.5, 3.5] (promedio por filas)

2.5
[1.5 3.5]


In [3]:
arr = np.array([[1, 2], [3, 4]])
print(np.min(arr))       # 1 (mínimo total)
print(np.min(arr, axis=0))  # [1, 2] (mínimo por columnas)

1
[1 2]


In [4]:
arr = np.array([[1, 2], [3, 4]])
print(np.max(arr))       # 4 (máximo total)
print(np.max(arr, axis=1))  # [2, 4] (máximo por filas)

4
[2 4]


In [10]:
arr = np.array([[1, 2], [3, 4]])
print(np.std(arr))       # 1.118 (desviación total)
print(np.std(arr, axis=0))  # [1., 1.] (desviación por columnas)

1.118033988749895
[1. 1.]


In [5]:
arr = np.array([[1, 2], [3, 4]])
print(np.var(arr))       # 1.25 (varianza total)
print(np.var(arr, axis=1))  # [0.25, 0.25] (varianza por filas)

1.25
[0.25 0.25]
